### ISSUE TITLE
Allow duplicate repo_url entries

### ISSUE THREAD

**Issue by jmertic** [cncf/landscapeapp#314]
Use case is for the Open Mainframe Landscape - see https://landscape.openmainframeproject.org/category=zowe-conformant&format=card-mode&grouping=category&organization=ibm

An offering can be in one or more categories. For commercial apps, I can get around the name duplication check by adding an extra identifier on the name. But for open source apps, I can't repeat a repo so have to leave the repo field blank on the other offerings and thus they won't pull GitHub info.

**Comment by dankohn** [comment]
We've had requests before to support multiple categories for a single item but have resisted because it would cause the total number of items to blow up. The great advantage of requiring uniqueness for `repo_url` is that it lets us avoid mistakes of accidentally adding the same thing twice.

In your case, would you be OK creating a new sub-category called `Multi-Function` or similar that would sit next to API Mediation Layer, App Framework, and CLI underneath Zowe Conformant?

Feel free to ping me on Slack to discuss.

**Comment by dankohn** [comment]
Please add support for an `allow_duplicate_repo: true` setting in individual landscape items which overrides the duplicate repo check.

**Comment by jordinl83** [comment]
@dankohn having to add `allow_duplicate_repo` seems unnecessary, why not just remove the duplicate repo check? 

An alternative approach and, in my opinion, preferable would be to re-structure `landscape.yml` to have `projects` at the top and each project have `categories`, instead of having `categories > subcategories > projects`.

So the new `landscape.yml` would look like this instead:

```yaml
projects:
  - name: Feilong
    homepage_url: 'https://www.openmainframeproject.org/projects/feilong'
    project: incubating
    repo_url: 'https://github.com/openmainframeproject/python-zvm-sdk'
    logo: feilong.svg
    categories: 
      - Projects: 
          - Linux
      - Zowe Conformant:
          - API Mediation Layer
          - App Framework
  - name: libica
    homepage_url: 'https://github.com/opencryptoki/libica'
    repo_url: 'https://github.com/opencryptoki/libica'
    logo: libica.svg
    crunchbase: 'https://www.crunchbase.com/organization/ibm'
    categories:
      - Projects:
          - z/OS
      - Open Mainframe Project Member Company:
          - Platinum
```
